language: ruby
sudo: false
cache: bundler
rvm:
  - ruby-head
  - 2.3.1
  - 2.2
  - 2.1
  - 2.0
before_install:
  - gem install bundler
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
